//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidsrapportServiceCaller.TidsrapporteringService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TidsrapporteringService.ITidsrapporteringService")]
    public interface ITidsrapporteringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITidsrapporteringService/GetData", ReplyAction="http://tempuri.org/ITidsrapporteringService/GetDataResponse")]
        string GetData(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ITidsrapporteringServiceChannel : TidsrapportServiceCaller.TidsrapporteringService.ITidsrapporteringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TidsrapporteringServiceClient : System.ServiceModel.ClientBase<TidsrapportServiceCaller.TidsrapporteringService.ITidsrapporteringService>, TidsrapportServiceCaller.TidsrapporteringService.ITidsrapporteringService {
        
        public TidsrapporteringServiceClient() {
        }
        
        public TidsrapporteringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TidsrapporteringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TidsrapporteringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TidsrapporteringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
    }
}
